
# SPDX-FileCopyrightText: 2021 Henrik Sandklef
#
# SPDX-License-Identifier: GPL-3.0-or-later


test:
	python3 -m unittest

clean:
	-find . -name "*.pyc" -o -name "*~" | xargs rm
	-find . -name "__pycache__" | xargs rm -fr
